config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#root'
  get 'signup',  to: 'users#new'
  get 'sessions/new'
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  post 'users/:id' => 'places#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
    collection do
      get :search # create a new path for the searching
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :places
end

app/models/user.rb
# frozen_string_literal: true

# Model of application's user
class User < ApplicationRecord
  attr_accessor :remember_token

  has_many :places, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: 'follower_id',
                                  inverse_of: :follower,
                                  dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'followed_id',
                                   inverse_of: :followed,
                                   dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 250 }, format:
      { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def self.search(params)
    if params[:search].present?
      users = User.where("lower(first_name) || ' ' || lower(last_name) like ?",
                         "%#{params[:search].downcase.strip.squeeze}%")
    end
    users # returns the users containing the search words
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# class Users controller
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[index edit update destroy following
                                          followers]
  before_action :correct_user,   only: %i[edit update]
  before_action :admin_user, only: :destroy

  def search
    if params[:search].blank?
      redirect_to users_url
    else
      @users = User.search(params)
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_url
  end

  def following
    @title = t('.followees')
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = t('.followers')
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    render 'edit'
  end

  private

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email,
                                 :password, :password_confirmation)
  end

  def logged_in_user
    return if logged_in?

    store_location
    flash[:danger] = t('.please_sign_in')
    redirect_to login_url
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.first_name, class: 'gravatar')
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <%= hidden_field_tag :followed_id, @user.id %>
  <%= f.submit t('.follow_button'), class: 'btn btn-outline-primary m-1 p-1 font-weight-bold' %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div class="ml-2 pt-3" id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_show_map.html.erb
<% if current_user?(@user) || current_user.following?(@user) %>
  <p class="d-inline-flex">
    <%= text_field_tag 'pac-input', nil, id: 'pac-input', class: 'form-control m-1 p-1 w-auto', placeholder: t('.locate') %>
    <select id="selectPlace" name="selectPlace" class="form-control w-auto m-1 p-1">
      <option class="select_placeholder" value="" hidden><%= t('.marked_places') %></option>
    </select>
  </p>
  <div class="map" id="map"></div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete }) do |f| %>
  <%= f.submit t('.unfollow_button'), class: 'btn btn-outline-secondary m-1 p-1' %>
<% end %>

app/views/users/_user.html.erb
<li class="p-1 list-unstyled">
  <%= link_to gravatar_for(user, size: 64), user %>
  <%= link_to "#{user.first_name} #{user.last_name}", user, style: 'font-size: 20px;' %>
  <% if current_user.admin? && !current_user?(user) %>
    <span class="lead">|</span> <%= link_to t('.delete'), user,
                            method: :delete,
                            id: 'user_deletion_link',
                            data: { confirm: "#{t('.delete_user')} \"#{user.first_name} #{user.last_name}\"?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% content_for :nav do %>
  <% if logged_in? %>
    <%= link_to t('.find_someone_button'), users_path, class: 'form-control btn btn-outline-primary my-2 my-sm-0 mr-2 ml-2' %>
    <%= link_to_unless_current(t('.my_places_button'), current_user, class: 'form-control btn btn-outline-primary my-2 my-sm-0 mr-2 ml-2') {} %>
    <%= link_to t('.sign_out_button'), logout_path,
                            method: :delete,
                            class: 'form-control btn btn-outline-secondary my-2 my-sm-0 mr-2 ml-2',
                            data: { confirm: t('.sign_out_confirmation') } %>
  <% else %>
  <% end %>
<% end %>

<% content_for :main do %>
<div class="container col-md-6">
  <h1><%= t('.my_profile_title') %></h1>
  <div class="gravatar_edit">
    <p>
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank" class="btn btn-outline-primary m-2 p-1"><%= t('.change_gravatar') %></a>
    </p>
  </div>
  <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
    <p>
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </p>
    <p>
      <%= f.submit t('.save_changes_button'), class: "btn btn-outline-success", data: { confirm: t('.save_changes_confirmation') } %>
    </p>
  <% end %>
</div>
<% end %>

app/views/users/index.html.erb
<% content_for :nav do %>
  <% if logged_in? %>
    <%= link_to t('.my_profile_button'), edit_user_path(current_user), class: 'form-control btn btn-outline-primary my-2 my-sm-0 mr-2 ml-2' %>
    <%= link_to_unless_current(t('.my_places_button'), current_user, class: 'form-control btn btn-outline-primary my-2 my-sm-0 mr-2 ml-2') {} %>
    <%= link_to t('.sign_out_button'), logout_path,
                            method: :delete,
                            class: 'form-control btn btn-outline-secondary my-2 my-sm-0 mr-2 ml-2',
                            data: { confirm: t('.sign_out_confirmation') } %>
  <% else %>
  <% end %>
<% end %>

<% content_for :main do %>
<h1><%= t('.all_users_title') %></h1>

<span class="pagination_span"><%= will_paginate %></span>

<%= form_tag search_users_path, method: :get, class: 'form-inline col-md-5' do %>
  <%= text_field_tag :search, nil, class: 'form-control m-1 w-75', autofocus: true %>
  <%= submit_tag t('.search_button'), class: 'btn btn-outline-success m-1' %>
<% end %>

<ul class="users">
  <%= render @users %>
</ul>

<span class="pagination_span"><%= will_paginate %></span>
<% end %>

app/views/users/new.html.erb
<% content_for :nav do %>
  <%= link_to t('.root_page_button'), '/',
                                     class: 'form-control btn btn-outline-secondary my-2 my-sm-0 mr-2 ml-2' %>
<% end %>

<% content_for :main do %>
<div class="container col-md-6">
  <h1><%= t('.sign_up_title') %></h1>
  <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
      <p>
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'form-control', autofocus: true %>
      </p>
      <p>
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control' %>
      </p>
      <p>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </p>
      <p>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </p>
      <p>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </p>
      <p>
        <%= f.submit t('.sign_up_button'), class: "btn btn-outline-success" %>
      </p>
    <% end %>
    <p> <%= t('.have_an_accout_already') %> <%= link_to t('.sign_in'), login_path %></p>
</div>
<% end %>

app/views/users/search.html.erb
<% content_for :nav do %>
  <% if logged_in? %>
    <%= link_to t('.my_profile_button'), edit_user_path(current_user), class: 'form-control btn btn-outline-primary my-2 my-sm-0 mr-2 ml-2' %>
    <%= link_to_unless_current(t('.my_places_button'), current_user, class: 'form-control btn btn-outline-primary my-2 my-sm-0 mr-2 ml-2') {} %>
    <%= link_to t('.sign_out_button'), logout_path,
                            method: :delete,
                            class: 'form-control btn btn-outline-secondary my-2 my-sm-0 mr-2 ml-2',
                            data: { confirm: t('.sign_out_confirmation') } %>
  <% else %>
  <% end %>
<% end %>

<% content_for :main do %>

<h1><%= t('.search_results') %></h1>

<p>
  <%= link_to t('.back_to_all'), users_path, class: 'btn btn-primary' %>
</p>

<% if @users.empty? %>
<h4><%= t('.no_one_was_found') %></h4>
<% else %>
<ul class="users">
  <%= render @users %>
</ul>
<% end %>

<% end %>

app/views/users/show.html.erb
<% content_for :nav do %>
  <% if logged_in? %>
    <%= link_to t('.find_someone_button'), users_path, class: 'form-control btn btn-outline-primary my-2 my-sm-0 mr-2 ml-2' %>
    <%= link_to t('.my_profile_button'), edit_user_path(current_user), class: 'form-control btn btn-outline-primary my-2 my-sm-0 mr-2 ml-2' %>
    <%= link_to_unless_current(t('.my_places_button'), current_user, class: 'form-control btn btn-outline-primary my-2 my-sm-0 mr-2 ml-2') {} %>
    <%= link_to t('.sign_out_button'), logout_path,
                            method: :delete,
                            class: 'form-control btn btn-outline-secondary my-2 my-sm-0 mr-2 ml-2',
                            data: { confirm: t('.sign_out_confirmation') } %>
  <% else %>
  <% end %>
<% end %>

<% content_for :main do %>
  <div class="d-inline-flex"><h1><%= gravatar_for @user %> <%= @user.first_name %></h1><%= render 'follow_form' if logged_in? %></div>
  <%= render 'shared/stats' %>
  <%= render 'show_map' %>
  <div class="formPlaces" id="formPlaces" hidden="true">
    <% if current_user?(@user) %>
    <%=render 'places/formCreate'%>
    <% end %>
    <%=render 'places/formUpdate'%>
    <%=render 'places/formView'%>
  </div>
<% end %>

app/views/users/show_follow.html.erb
<% content_for :nav do %>
  <% if logged_in? %>
    <%= link_to t('.find_someone_button'), users_path, class: 'form-control btn btn-outline-primary my-2 my-sm-0 mr-2 ml-2' %>
    <%= link_to t('.my_profile_button'), edit_user_path(current_user), class: 'form-control btn btn-outline-primary my-2 my-sm-0 mr-2 ml-2' %>
    <%= link_to_unless_current(t('.my_places_button'), current_user, class: 'form-control btn btn-outline-primary my-2 my-sm-0 mr-2 ml-2') {} %>
    <%= link_to t('.sign_out_button'), logout_path,
                            method: :delete,
                            class: 'form-control btn btn-outline-secondary my-2 my-sm-0 mr-2 ml-2',
                            data: { confirm: t('.sign_out_confirmation') } %>
  <% else %>
  <% end %>
<% end %>

<% content_for :main do %>
  <div class="d-inline-flex"><h1><%= gravatar_for @user %> <%= @user.first_name %></h1><%= render 'follow_form' if logged_in? %></div>
  <%= render 'shared/stats' %>
  <% if @users.any? %>
    <div class="user_avatars pt-2">
    <% @users.each do |user| %>
      <%= link_to gravatar_for(user, size: 48), user, title: user.first_name, class: 'pl-1' %>
    <% end %>
    </div>
  <% end %>
  <div class="pt-2"><h3><%= @title %></h3></div>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
    <% end %>
<% end %>